version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: github-inventory-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meddlin
      POSTGRES_PASSWORD: jailbreak
      POSTGRES_DB: github_inventory
    volumes:
      - ./postgres-data:/var/lib/postgresql/data   # persistent data stored locally
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-meddlin} -d ${POSTGRES_DB:-github_inventory}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: github-inventory-pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: drushing.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: jailbreak
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin