from typing import Any, List
from github_cli.models.owner import GitHubOwner

class GitHubRepository:
    def __init__(
            self,
            id: int | None = None,
            node_id: str = "",
            name: str = "",
            full_name: str = "",
            private: bool | None = None,
            owner: GitHubOwner | None = None,
            html_url: str = "",
            description: str = "",
            fork: bool | None = None,
            url: str = "",
            forks_url: str = "",
            keys_url: str = "",
            collaborators_url: str = "",
            teams_url: str = "",
            hooks_url: str = "",
            issue_events_url: str = "",
            events_url: str = "",
            assignees_url: str = "",
            branches_url: str = "",
            tags_url: str = "",
            blobs_url: str = "",
            git_tags_url: str = "",
            git_refs_url: str = "",
            trees_url: str = "",
            statuses_url: str = "",
            languages_url: str = "",
            stargazers_url: str = "",
            contributors_url: str = "",
            cubscribers_url: str = "",
            subscription_url: str = "",
            commits_url: str = "",
            issue_comment_url: str = "",
            contents_url: str = "",
            compare_url: str = "",
            merges_url: str = "",
            archive_url: str = "",
            downloads_url: str = "",
            issues_url: str = "",
            pulls_url: str = "",
            milestones_url: str = "",
            notifications_url: str = "",
            labels_url: str = "",
            releases_url: str = "",
            deployments_url: str = "",
            created_at: str = "",
            updated_at: str = "",
            pushed_at: str = "",
            git_url: str = "",
            ssh_url: str = "",
            clone_url: str = "",
            svn_url: str = "",
            homepage: Any = None,
            size: int | None = None,
            stargazers_count: int | None = None,
            watchers_count: int | None = None,
            language: str = "",
            has_issues: bool | None = None,
            has_projects: bool | None = None,
            has_downloads: bool | None = None,
            has_wiki: bool | None = None,
            has_pages: bool | None = None,
            has_discussions: bool | None = None,
            forks_count: int | None = None,
            mirror_url: str = "",
            archived: bool | None = None,
            disabled: bool | None = None,
            open_issues_count: int | None = None,
            license: str = "",
            allow_forking: bool | None = None,
            is_template: bool | None = None,
            web_commit_signoff_required: bool | None = None,
            topics: List[Any] | None = None,
            visibility: str = "",
            forks: int | None = None,
            open_issues: int| None = None,
            watchers: int | None = None,
            default_branch: str = "",
        #     permissions: GitHubRepoPermissions
    ):
        self.id = id
        self.node_id = node_id
        self.name = name
        self.full_name = full_name
        self.private = private
        self.owner = owner
        self.html_url = html_url
        self.description = description
        self.fork = fork
        self.url = url
        self.forks_url = forks_url
        self.keys_url = keys_url
        self.collaborators_url = collaborators_url
        self.teams_url = teams_url
        self.hooks_url = hooks_url
        self.issue_events_url = issue_events_url
        self.events_url = events_url
        self.assignees_url = assignees_url
        self.branches_url = branches_url
        self.tags_url = tags_url
        self.blobs_url = blobs_url
        self.git_tags_url = git_tags_url
        self.git_refs_url = git_refs_url
        self.trees_url = trees_url
        self.statuses_url = statuses_url
        self.languages_url = languages_url
        self.stargazers_url = stargazers_url
        self.contributors_url = contributors_url
        self.cubscribers_url = cubscribers_url
        self.subscription_url = subscription_url
        self.commits_url = commits_url
        self.issue_comment_url = issue_comment_url
        self.contents_url = contents_url
        self.compare_url = compare_url
        self.merges_url = merges_url
        self.archive_url = archive_url
        self.downloads_url = downloads_url
        self.issues_url = issues_url
        self.pulls_url = pulls_url
        self.milestones_url = milestones_url
        self.notifications_url = notifications_url
        self.labels_url = labels_url
        self.releases_url = releases_url
        self.deployments_url = deployments_url
        self.created_at = created_at
        self.updated_at = updated_at
        self.pushed_at = pushed_at
        self.git_url = git_url
        self.ssh_url = ssh_url
        self.clone_url = clone_url
        self.svn_url = svn_url
        self.homepage = homepage
        self.size = size
        self.stargazers_count = stargazers_count
        self.watchers_count = watchers_count
        self.language = language
        self.has_issues = has_issues
        self.has_projects = has_projects
        self.has_downloads = has_downloads
        self.has_wiki = has_wiki
        self.has_pages = has_pages
        self.has_discussions = has_discussions
        self.forks_count = forks_count
        self.mirror_url = mirror_url
        self.archived = archived
        self.disabled = disabled
        self.open_issues_count = open_issues_count
        self.license = license
        self.allow_forking = allow_forking
        self.is_template = is_template
        self.web_commit_signoff_required = web_commit_signoff_required
        self.topics = topics
        self.visibility = visibility
        self.forks = forks
        self.open_issues = open_issues
        self.watchers = watchers
        self.default_branch = default_branch